* CLUSTERED COPY of 02_hetero.do generated by _make_cl_dofiles.py (vce -> cluster(isocode); outputs *_results_cl.csv)
capture log close _all
log using "02_hetero_cl_run.log", replace text
do "_prep.doh"
tempname fh
file open `fh' using "_hetero_results_cl.csv", write replace
file write `fh' "block,treat,outcome,term,b,se,p,kpf,N" _n
foreach tr in ln_gaci_max ln_gaci_cwm {
foreach yv in ln_gini_mkt ln_gini_disp {
    * A. baseline-income terciles, interaction IV
    ivreghdfe `yv' lnpop (`tr' `tr'_mid `tr'_high = feyrer_int feyrer_int_mid feyrer_int_high), absorb(isocode y) cluster(isocode)
    local kp = e(widstat)
    local nn = e(N)
    foreach t in `tr' `tr'_mid `tr'_high {
        local b = _b[`t']
        local se = _se[`t']
        local p = 2*normal(-abs(_b[`t']/_se[`t']))
        file write `fh' "inc3,`tr',`yv',`t',`b',`se',`p',`kp',`nn'" _n
    }
    lincom `tr' + `tr'_mid
    file write `fh' "inc3,`tr',`yv',mid_total,`r(estimate)',`r(se)',`r(p)',.,`nn'" _n
    lincom `tr' + `tr'_high
    file write `fh' "inc3,`tr',`yv',high_total,`r(estimate)',`r(se)',`r(p)',.,`nn'" _n
    * A2. separate by tercile
    forvalues q = 1/3 {
        capture ivreghdfe `yv' lnpop (`tr' = feyrer_int) if inc3==`q', absorb(isocode y) cluster(isocode)
        if _rc==0 {
            local b = _b[`tr']
            local se = _se[`tr']
            local p = 2*normal(-abs(_b[`tr']/_se[`tr']))
            local kp = e(widstat)
            local nn = e(N)
            file write `fh' "inc3_split,`tr',`yv',q`q',`b',`se',`p',`kp',`nn'" _n
        }
    }
    * B. baseline-inequality terciles
    ivreghdfe `yv' lnpop (`tr' `tr'_g2 `tr'_g3 = feyrer_int feyrer_int_g2 feyrer_int_g3), absorb(isocode y) cluster(isocode)
    local kp = e(widstat)
    local nn = e(N)
    foreach t in `tr' `tr'_g2 `tr'_g3 {
        local b = _b[`t']
        local se = _se[`t']
        local p = 2*normal(-abs(_b[`t']/_se[`t']))
        file write `fh' "gini3,`tr',`yv',`t',`b',`se',`p',`kp',`nn'" _n
    }
    lincom `tr' + `tr'_g2
    file write `fh' "gini3,`tr',`yv',g2_total,`r(estimate)',`r(se)',`r(p)',.,`nn'" _n
    lincom `tr' + `tr'_g3
    file write `fh' "gini3,`tr',`yv',g3_total,`r(estimate)',`r(se)',`r(p)',.,`nn'" _n
    * C. temporal post-2010
    ivreghdfe `yv' lnpop (`tr' `tr'_post = feyrer_int feyrer_int_post), absorb(isocode y) cluster(isocode)
    local kp = e(widstat)
    local nn = e(N)
    foreach t in `tr' `tr'_post {
        local b = _b[`t']
        local se = _se[`t']
        local p = 2*normal(-abs(_b[`t']/_se[`t']))
        file write `fh' "post2010,`tr',`yv',`t',`b',`se',`p',`kp',`nn'" _n
    }
    lincom `tr' + `tr'_post
    file write `fh' "post2010,`tr',`yv',post_total,`r(estimate)',`r(se)',`r(p)',.,`nn'" _n
    * D. by continent (separate 2SLS)
    levelsof cont, local(cl)
    foreach cc of local cl {
        capture ivreghdfe `yv' lnpop (`tr' = feyrer_int) if cont=="`cc'", absorb(isocode y) cluster(isocode)
        if _rc==0 {
            local b = _b[`tr']
            local se = _se[`tr']
            local p = 2*normal(-abs(_b[`tr']/_se[`tr']))
            local kp = e(widstat)
            local nn = e(N)
            file write `fh' "continent,`tr',`yv',`cc',`b',`se',`p',`kp',`nn'" _n
        }
    }
}
}
file close `fh'
log close
