* CLUSTERED COPY of 03_conc_mech.do generated by _make_cl_dofiles.py (vce -> cluster(isocode); outputs *_results_cl.csv)
capture log close _all
log using "03_conc_mech_cl_run.log", replace text
do "_prep.doh"
tempname fh
file open `fh' using "_conc_mech_results_cl.csv", write replace
file write `fh' "block,outcome,term,model,b,se,p,kpf,N" _n
foreach yv in ln_gini_mkt ln_gini_disp {
    * --- Concentration block ---
    reghdfe `yv' ln_share_max lnpop, absorb(isocode y) vce(cluster isocode)
    local b = _b[ln_share_max]
    local se = _se[ln_share_max]
    local p = 2*ttail(e(df_r), abs(_b[ln_share_max]/_se[ln_share_max]))
    local nn = e(N)
    file write `fh' "conc,`yv',ln_share_max,OLS_alone,`b',`se',`p',.,`nn'" _n
    reghdfe `yv' ln_share_max ln_gaci_sum lnpop, absorb(isocode y) vce(cluster isocode)
    local nn = e(N)
    foreach t in ln_share_max ln_gaci_sum {
        local b = _b[`t']
        local se = _se[`t']
        local p = 2*ttail(e(df_r), abs(_b[`t']/_se[`t']))
        file write `fh' "conc,`yv',`t',OLS_withsum,`b',`se',`p',.,`nn'" _n
    }
    reghdfe `yv' ln_hhi ln_gaci_sum lnpop, absorb(isocode y) vce(cluster isocode)
    local nn = e(N)
    foreach t in ln_hhi ln_gaci_sum {
        local b = _b[`t']
        local se = _se[`t']
        local p = 2*ttail(e(df_r), abs(_b[`t']/_se[`t']))
        file write `fh' "conc,`yv',`t',OLS_hhi,`b',`se',`p',.,`nn'" _n
    }
    reghdfe `yv' ln_gaci_max ln_gaci_mean lnpop, absorb(isocode y) vce(cluster isocode)
    local nn = e(N)
    foreach t in ln_gaci_max ln_gaci_mean {
        local b = _b[`t']
        local se = _se[`t']
        local p = 2*ttail(e(df_r), abs(_b[`t']/_se[`t']))
        file write `fh' "conc,`yv',`t',OLS_max_mean,`b',`se',`p',.,`nn'" _n
    }
    * IV: max instrumented, sum as control
    ivreghdfe `yv' lnpop ln_gaci_sum (ln_gaci_max = feyrer_int), absorb(isocode y) cluster(isocode)
    local kp = e(widstat)
    local nn = e(N)
    foreach t in ln_gaci_max ln_gaci_sum {
        local b = _b[`t']
        local se = _se[`t']
        local p = 2*normal(-abs(_b[`t']/_se[`t']))
        file write `fh' "conc,`yv',`t',IV_max_ctrl_sum,`b',`se',`p',`kp',`nn'" _n
    }
    * IV: two endogenous (max, sum) with two instruments
    ivreghdfe `yv' lnpop (ln_gaci_max ln_gaci_sum = feyrer_int tourism_int), absorb(isocode y) cluster(isocode)
    local kp = e(widstat)
    local nn = e(N)
    foreach t in ln_gaci_max ln_gaci_sum {
        local b = _b[`t']
        local se = _se[`t']
        local p = 2*normal(-abs(_b[`t']/_se[`t']))
        file write `fh' "conc,`yv',`t',IV_two_endog,`b',`se',`p',`kp',`nn'" _n
    }
    * IV interaction: concentrated (baseline share_max>0.5) vs distributed systems
    ivreghdfe `yv' lnpop (ln_gaci_max ln_gaci_max_conc = feyrer_int feyrer_int_conc), absorb(isocode y) cluster(isocode)
    local kp = e(widstat)
    local nn = e(N)
    foreach t in ln_gaci_max ln_gaci_max_conc {
        local b = _b[`t']
        local se = _se[`t']
        local p = 2*normal(-abs(_b[`t']/_se[`t']))
        file write `fh' "conc,`yv',`t',IV_x_conc,`b',`se',`p',`kp',`nn'" _n
    }
    lincom ln_gaci_max + ln_gaci_max_conc
    file write `fh' "conc,`yv',conc_total,IV_x_conc,`r(estimate)',`r(se)',`r(p)',.,`nn'" _n
    * --- Mechanism block: mediator on connectivity (2SLS), then c vs c-prime ---
    foreach m in emp_srv emp_ind emp_agr primacy urban ln_gdppc trade_gdp fdi_gdp tax_gdp ter_enr unemp {
        capture ivreghdfe `m' lnpop (ln_gaci_max = feyrer_int), absorb(isocode y) cluster(isocode)
        if _rc==0 {
            local b = _b[ln_gaci_max]
            local se = _se[ln_gaci_max]
            local p = 2*normal(-abs(_b[ln_gaci_max]/_se[ln_gaci_max]))
            local kp = e(widstat)
            local nn = e(N)
            file write `fh' "mech_a,`m',ln_gaci_max,IV,`b',`se',`p',`kp',`nn'" _n
            ivreghdfe `yv' lnpop (ln_gaci_max = feyrer_int) if !missing(`m'), absorb(isocode y) cluster(isocode)
            local c0 = _b[ln_gaci_max]
            local n0 = e(N)
            ivreghdfe `yv' lnpop `m' (ln_gaci_max = feyrer_int), absorb(isocode y) cluster(isocode)
            local b = _b[ln_gaci_max]
            local se = _se[ln_gaci_max]
            local p = 2*normal(-abs(_b[ln_gaci_max]/_se[ln_gaci_max]))
            local bm = _b[`m']
            local sem = _se[`m']
            local pm = 2*normal(-abs(_b[`m']/_se[`m']))
            local kp = e(widstat)
            local nn = e(N)
            file write `fh' "mech_c,`yv'_`m',c,IV,`c0',.,.,.,`n0'" _n
            file write `fh' "mech_c,`yv'_`m',cprime,IV,`b',`se',`p',`kp',`nn'" _n
            file write `fh' "mech_c,`yv'_`m',b_mediator,IV,`bm',`sem',`pm',.,`nn'" _n
        }
    }
}
file close `fh'
log close
