* CLUSTERED COPY of 09_gdp.do generated by _make_cl_dofiles.py (vce -> cluster(isocode); outputs *_results_cl.csv)
* 09_gdp.do : Growth outcomes (GDP and WID income levels) placed beside the inequality results.
* Mirrors 01_main / 02_hetero / 04_longdiff / 05_robust / 07_diag specifications exactly,
* so every growth estimate is the twin of an inequality estimate already in the paper.
capture log close _all
log using "09_gdp_cl_run.log", replace text
do "_prep.doh"
set varabbrev off

* growth-incidence gap: log gap between top-decile and bottom-half average income
gen ln_ratio_avg = ln_avg_top10_wid - ln_avg_bot50_wid
label var ln_ratio_avg "ln(avg top10 / avg bot50)"

* exposure x trend controls, same construction as 07_diag.do
gen at_basepc = a_t*basepc
gen at_basegini = a_t*basegini
gen at_lnland = a_t*lnland
gen at_abslat = a_t*abslat
gen at_seama = a_t*ln_sea_ma
bysort isocode (y): gen basetrade = trade_share[1]
gen at_basetrade = a_t*basetrade

tempname fh
file open `fh' using "_gdp_results_cl.csv", write replace
file write `fh' "block,outcome,treat,iv,spec,b,se,p,kpf,hansenp,N" _n

local GY "ln_gdppc lngdp ln_avg_all_wid ln_avg_bot50_wid ln_avg_top10_wid ln_ratio_avg"

* ---------------------------------------------------------------- A. main table twin
foreach ivv in feyrer_int tourism_int {
foreach tr in ln_gaci_max ln_gaci_cwm ln_gaci_sum {
    foreach yv of local GY {
        reghdfe `yv' `tr' lnpop, absorb(isocode y) vce(cluster isocode)
        local bb = _b[`tr']
        local ss = _se[`tr']
        local pp = 2*ttail(e(df_r), abs(`bb'/`ss'))
        local nn = e(N)
        file write `fh' "main,`yv',`tr',`ivv',OLS,`bb',`ss',`pp',.,.,`nn'" _n
        ivreghdfe `yv' lnpop (`tr' = `ivv'), absorb(isocode y) cluster(isocode)
        local bb = _b[`tr']
        local ss = _se[`tr']
        local pp = 2*normal(-abs(`bb'/`ss'))
        local kp = e(widstat)
        local nn = e(N)
        file write `fh' "main,`yv',`tr',`ivv',IV,`bb',`ss',`pp',`kp',.,`nn'" _n
        ivreghdfe `yv' lnpop (`tr' = `ivv'), absorb(isocode y) cluster(isocode)
        local bb = _b[`tr']
        local ss = _se[`tr']
        local pp = 2*normal(-abs(`bb'/`ss'))
        local kp = e(widstat)
        local nn = e(N)
        file write `fh' "main,`yv',`tr',`ivv',IVcl,`bb',`ss',`pp',`kp',.,`nn'" _n
    }
}
}

* ---------------------------------------------------------------- B. over-identified and controls
foreach yv of local GY {
    ivreghdfe `yv' lnpop (ln_gaci_max = feyrer_int tourism_int), absorb(isocode y) cluster(isocode)
    local bb = _b[ln_gaci_max]
    local ss = _se[ln_gaci_max]
    local pp = 2*normal(-abs(`bb'/`ss'))
    local kp = e(widstat)
    local jp = e(jp)
    local nn = e(N)
    file write `fh' "overid,`yv',ln_gaci_max,both,feyrer_tourism,`bb',`ss',`pp',`kp',`jp',`nn'" _n
}
local ci = 0
foreach ctrl in "none" "urban" "ter_enr" "trade_gdp" "tax_gdp" "ln_sea_ma" "urban ter_enr trade_gdp" {
    local ci = `ci' + 1
    local cv = "`ctrl'"
    if "`ctrl'"=="none" local cv = ""
    foreach yv in ln_gdppc ln_avg_bot50_wid {
        ivreghdfe `yv' lnpop `cv' (ln_gaci_max = feyrer_int), absorb(isocode y) cluster(isocode)
        local bb = _b[ln_gaci_max]
        local ss = _se[ln_gaci_max]
        local pp = 2*normal(-abs(`bb'/`ss'))
        local kp = e(widstat)
        local nn = e(N)
        file write `fh' "controls,`yv',ln_gaci_max,feyrer_int,ctrl`ci',`bb',`ss',`pp',`kp',.,`nn'" _n
    }
}

* ---------------------------------------------------------------- C. identification diagnostics
foreach yv in ln_gdppc ln_avg_bot50_wid ln_avg_top10_wid ln_ratio_avg {
    foreach ivv in feyrer_int tourism_int {
        ivreghdfe `yv' lnpop (ln_gaci_max = `ivv'), absorb(isocode contid#y) cluster(isocode)
        local bb = _b[ln_gaci_max]
        local ss = _se[ln_gaci_max]
        local pp = 2*normal(-abs(`bb'/`ss'))
        local kp = e(widstat)
        local nn = e(N)
        file write `fh' "diag,`yv',ln_gaci_max,`ivv',cont_x_year,`bb',`ss',`pp',`kp',.,`nn'" _n
        ivreghdfe `yv' lnpop (ln_gaci_max = `ivv') if cont!="LA", absorb(isocode contid#y) cluster(isocode)
        local bb = _b[ln_gaci_max]
        local ss = _se[ln_gaci_max]
        local pp = 2*normal(-abs(`bb'/`ss'))
        local kp = e(widstat)
        local nn = e(N)
        file write `fh' "diag,`yv',ln_gaci_max,`ivv',cont_x_year_dropLA,`bb',`ss',`pp',`kp',.,`nn'" _n
        ivreghdfe `yv' lnpop at_basepc at_basegini at_lnland at_abslat (ln_gaci_max = `ivv'), absorb(isocode y) cluster(isocode)
        local bb = _b[ln_gaci_max]
        local ss = _se[ln_gaci_max]
        local pp = 2*normal(-abs(`bb'/`ss'))
        local kp = e(widstat)
        local nn = e(N)
        file write `fh' "diag,`yv',ln_gaci_max,`ivv',exposure_trend,`bb',`ss',`pp',`kp',.,`nn'" _n
        ivreghdfe `yv' lnpop at_basepc at_basegini at_lnland at_abslat at_seama at_basetrade (ln_gaci_max = `ivv'), absorb(isocode contid#y) cluster(isocode)
        local bb = _b[ln_gaci_max]
        local ss = _se[ln_gaci_max]
        local pp = 2*normal(-abs(`bb'/`ss'))
        local kp = e(widstat)
        local nn = e(N)
        file write `fh' "diag,`yv',ln_gaci_max,`ivv',kitchen_sink,`bb',`ss',`pp',`kp',.,`nn'" _n
    }
}

* ---------------------------------------------------------------- D. horizon and leads
foreach yv in ln_gdppc ln_avg_bot50_wid ln_avg_top10_wid ln_ratio_avg {
    forvalues k = 0/10 {
        capture ivreghdfe `yv' lnpop (L`k'.ln_gaci_max = L`k'.feyrer_int), absorb(isocode y) cluster(isocode)
        if _rc==0 {
            local bb = _b[L`k'.ln_gaci_max]
            local ss = _se[L`k'.ln_gaci_max]
            local pp = 2*normal(-abs(`bb'/`ss'))
            local kp = e(widstat)
            local nn = e(N)
            file write `fh' "lag,`yv',ln_gaci_max,feyrer_int,k`k',`bb',`ss',`pp',`kp',.,`nn'" _n
        }
    }
    forvalues k = 1/5 {
        capture ivreghdfe `yv' lnpop (F`k'.ln_gaci_max = F`k'.feyrer_int), absorb(isocode y) cluster(isocode)
        if _rc==0 {
            local bb = _b[F`k'.ln_gaci_max]
            local ss = _se[F`k'.ln_gaci_max]
            local pp = 2*normal(-abs(`bb'/`ss'))
            local kp = e(widstat)
            local nn = e(N)
            file write `fh' "lead,`yv',ln_gaci_max,feyrer_int,f`k',`bb',`ss',`pp',`kp',.,`nn'" _n
        }
    }
}

* ---------------------------------------------------------------- E. long differences
foreach yv in ln_gdppc ln_avg_bot50_wid ln_avg_top10_wid ln_ratio_avg {
    foreach pair in "1996 2019" "1996 2023" "2000 2019" "2005 2019" "2010 2019" {
        local y0 : word 1 of `pair'
        local y1 : word 2 of `pair'
        preserve
        keep if inlist(y, `y0', `y1')
        bysort isocode: keep if _N==2
        bysort isocode (y): gen dY = `yv'[2]-`yv'[1]
        bysort isocode (y): gen dX = ln_gaci_max[2]-ln_gaci_max[1]
        bysort isocode (y): gen dZ = feyrer_int[2]-feyrer_int[1]
        bysort isocode (y): gen dP = lnpop[2]-lnpop[1]
        bysort isocode (y): gen dT = tourism_int[2]-tourism_int[1]
        bysort isocode (y): keep if _n==1
        capture reg dY dX dP i.contid, robust
        if _rc==0 {
            local bb = _b[dX]
            local ss = _se[dX]
            local pp = 2*ttail(e(df_r), abs(`bb'/`ss'))
            local nn = e(N)
            file write `fh' "LD_OLS,`yv',ln_gaci_max,none,`y0'_`y1',`bb',`ss',`pp',.,.,`nn'" _n
        }
        capture ivreg2 dY dP i.contid (dX = dZ), robust
        if _rc==0 {
            local bb = _b[dX]
            local ss = _se[dX]
            local pp = 2*normal(-abs(`bb'/`ss'))
            local kp = e(widstat)
            local nn = e(N)
            file write `fh' "LD_IV,`yv',ln_gaci_max,feyrer_int,`y0'_`y1',`bb',`ss',`pp',`kp',.,`nn'" _n
        }
        capture ivreg2 dY dP i.contid (dX = dT), robust
        if _rc==0 {
            local bb = _b[dX]
            local ss = _se[dX]
            local pp = 2*normal(-abs(`bb'/`ss'))
            local kp = e(widstat)
            local nn = e(N)
            file write `fh' "LD_IVtour,`yv',ln_gaci_max,tourism_int,`y0'_`y1',`bb',`ss',`pp',`kp',.,`nn'" _n
        }
        restore
    }
    preserve
    gen dY = `yv' - L5.`yv'
    gen dX = ln_gaci_max - L5.ln_gaci_max
    gen dZ = feyrer_int - L5.feyrer_int
    gen dP = lnpop - L5.lnpop
    keep if !missing(dY, dX, dZ)
    capture reghdfe dY dX dP, absorb(y contid) cluster(isocode)
    if _rc==0 {
        local bb = _b[dX]
        local ss = _se[dX]
        local pp = 2*ttail(e(df_r), abs(`bb'/`ss'))
        local nn = e(N)
        file write `fh' "D5_OLS,`yv',ln_gaci_max,none,stacked5,`bb',`ss',`pp',.,.,`nn'" _n
    }
    capture ivreghdfe dY dP (dX = dZ), absorb(y contid) cluster(isocode)
    if _rc==0 {
        local bb = _b[dX]
        local ss = _se[dX]
        local pp = 2*normal(-abs(`bb'/`ss'))
        local kp = e(widstat)
        local nn = e(N)
        file write `fh' "D5_IV,`yv',ln_gaci_max,feyrer_int,stacked5,`bb',`ss',`pp',`kp',.,`nn'" _n
    }
    restore
}

* ---------------------------------------------------------------- F. heterogeneity
foreach yv in ln_gdppc ln_avg_bot50_wid ln_avg_top10_wid {
    ivreghdfe `yv' lnpop (ln_gaci_max ln_gaci_max_mid ln_gaci_max_high = feyrer_int feyrer_int_mid feyrer_int_high), absorb(isocode y) cluster(isocode)
    local kp = e(widstat)
    local nn = e(N)
    foreach t in ln_gaci_max ln_gaci_max_mid ln_gaci_max_high {
        local bb = _b[`t']
        local ss = _se[`t']
        local pp = 2*normal(-abs(`bb'/`ss'))
        file write `fh' "inc3,`yv',`t',feyrer_int,interaction,`bb',`ss',`pp',`kp',.,`nn'" _n
    }
    lincom ln_gaci_max + ln_gaci_max_mid
    file write `fh' "inc3,`yv',mid_total,feyrer_int,interaction,`r(estimate)',`r(se)',`r(p)',.,.,`nn'" _n
    lincom ln_gaci_max + ln_gaci_max_high
    file write `fh' "inc3,`yv',high_total,feyrer_int,interaction,`r(estimate)',`r(se)',`r(p)',.,.,`nn'" _n
    ivreghdfe `yv' lnpop (ln_gaci_max ln_gaci_max_post = feyrer_int feyrer_int_post), absorb(isocode y) cluster(isocode)
    local kp = e(widstat)
    local nn = e(N)
    foreach t in ln_gaci_max ln_gaci_max_post {
        local bb = _b[`t']
        local ss = _se[`t']
        local pp = 2*normal(-abs(`bb'/`ss'))
        file write `fh' "post2010,`yv',`t',feyrer_int,interaction,`bb',`ss',`pp',`kp',.,`nn'" _n
    }
    lincom ln_gaci_max + ln_gaci_max_post
    file write `fh' "post2010,`yv',post_total,feyrer_int,interaction,`r(estimate)',`r(se)',`r(p)',.,.,`nn'" _n
    levelsof cont, local(cl)
    foreach cc of local cl {
        capture ivreghdfe `yv' lnpop (ln_gaci_max = feyrer_int) if cont=="`cc'", absorb(isocode y) cluster(isocode)
        if _rc==0 {
            local bb = _b[ln_gaci_max]
            local ss = _se[ln_gaci_max]
            local pp = 2*normal(-abs(`bb'/`ss'))
            local kp = e(widstat)
            local nn = e(N)
            file write `fh' "continent,`yv',ln_gaci_max,feyrer_int,`cc',`bb',`ss',`pp',`kp',.,`nn'" _n
        }
    }
}

* ---------------------------------------------------------------- G. growth-conditional inequality
* inequality response holding measured income per head fixed
foreach yv in ln_gini_mkt ln_gini_disp {
    ivreghdfe `yv' lnpop ln_gdppc (ln_gaci_max = feyrer_int), absorb(isocode y) cluster(isocode)
    local kp = e(widstat)
    local nn = e(N)
    local bb = _b[ln_gaci_max]
    local ss = _se[ln_gaci_max]
    local pp = 2*normal(-abs(`bb'/`ss'))
    file write `fh' "joint,`yv',ln_gaci_max,feyrer_int,cond_gdp,`bb',`ss',`pp',`kp',.,`nn'" _n
    local bb = _b[ln_gdppc]
    local ss = _se[ln_gdppc]
    local pp = 2*normal(-abs(`bb'/`ss'))
    file write `fh' "joint,`yv',ln_gdppc,feyrer_int,cond_gdp,`bb',`ss',`pp',.,.,`nn'" _n
}
file close `fh'
log close
