# -*- coding: utf-8 -*-
"""Country-clustered copies of 01-07 and 09 (08 is already clustered).
   vce(robust) -> vce(cluster isocode); ', absorb(...) robust' -> ', absorb(...) cluster(isocode)'
   outputs *_results_cl.csv, logs *_cl_run.log. 07 additionally gets a sub-region x year FE block.
   Cross-section long-difference lines (reg/ivreg2 ..., robust) are left as robust: one obs per country."""
import io, os, re

D = os.path.dirname(os.path.abspath(__file__))
SRC = ["01_main", "02_hetero", "03_conc_mech", "04_longdiff", "05_robust", "06_tails", "07_diag", "09_gdp"]

SUBREG_BLOCK = r'''
* B9. sub-region x year FE (17 UN-type sub-regions in `reg'), added in the clustered copy
foreach yv in ln_gini_mkt ln_gini_disp {
    foreach ivv in feyrer_int tourism_int {
        ivreghdfe `yv' lnpop (ln_gaci_max = `ivv'), absorb(isocode regid#y) cluster(isocode)
        local b = _b[ln_gaci_max]
        local se = _se[ln_gaci_max]
        local p = 2*normal(-abs(`b'/`se'))
        local kp = e(widstat)
        local nn = e(N)
        file write `fh' "pooled,`yv',`ivv',subreg_x_year,`b',`se',`p',`kp',`nn'" _n
        ivreghdfe `yv' lnpop at_basepc at_basegini at_lnland at_abslat at_seama at_basetrade (ln_gaci_max = `ivv'), absorb(isocode regid#y) cluster(isocode)
        local b = _b[ln_gaci_max]
        local se = _se[ln_gaci_max]
        local p = 2*normal(-abs(`b'/`se'))
        local kp = e(widstat)
        local nn = e(N)
        file write `fh' "pooled,`yv',`ivv',exposure_trends_subregyear,`b',`se',`p',`kp',`nn'" _n
    }
    reghdfe `yv' ln_gaci_max lnpop, absorb(isocode regid#y) vce(cluster isocode)
    local b = _b[ln_gaci_max]
    local se = _se[ln_gaci_max]
    local p = 2*ttail(e(df_r), abs(`b'/`se'))
    local nn = e(N)
    file write `fh' "pooled,`yv',OLS,subreg_x_year,`b',`se',`p',.,`nn'" _n
    * first stage under sub-region x year FE
    reghdfe ln_gaci_max feyrer_int lnpop, absorb(isocode regid#y) vce(cluster isocode)
    local b = _b[feyrer_int]
    local se = _se[feyrer_int]
    local p = 2*ttail(e(df_r), abs(`b'/`se'))
    local nn = e(N)
    file write `fh' "pooled,ln_gaci_max,feyrer_int,FS_subreg_x_year,`b',`se',`p',.,`nn'" _n
}
'''

for s in SRC:
    t = io.open(os.path.join(D, s + ".do"), encoding="utf-8").read()
    n0 = t.count("robust")
    t = t.replace("vce(robust)", "vce(cluster isocode)")
    t = re.sub(r"(, absorb\([^)]*\)) robust\b", r"\1 cluster(isocode)", t)
    # panel ivreghdfe lines without absorb are not present; cross-section reg/ivreg2 robust lines stay
    t = t.replace("_results.csv\"", "_results_cl.csv\"")
    t = t.replace("_run.log\"", "_cl_run.log\"")
    if s == "07_diag":
        t = t.replace('do "_prep.doh"\n', 'do "_prep.doh"\nencode reg, gen(regid)\n', 1)
        t = t.replace("file close `fh'", SUBREG_BLOCK + "file close `fh'", 1)
    hdr = "* CLUSTERED COPY of %s.do generated by _make_cl_dofiles.py (vce -> cluster(isocode); outputs *_results_cl.csv)\n" % s
    io.open(os.path.join(D, s + "_cl.do"), "w", encoding="utf-8", newline="\n").write(hdr + t)
    print("%s_cl.do  robust tokens %d -> %d" % (s, n0, t.count("robust")))
