# -*- coding: utf-8 -*-
"""
_make_cl_dofiles.py   (2026-09-03) Country-clustered copies of the estimation do-files.
Replaces ') robust' after absorb(...) and 'vce(robust)' by cluster(isocode), and
appends _cl to every exported CSV name. Runs nothing; writes <name>_cl.do.
"""
import os, re, sys
sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
BS = chr(92)
FILES = ["co2_allestimators.do", "co2_extensions.do", "co2_temporal_excovid.do", "co2_temporal_pre2008.do",
         "co2_feyrer_mechanism.do", "co2_decomp_hetero.do", "co2_feyrer_hetero_tot.do", "co2_exclusion_suite.do",
         "co2_spill_bands.do", "co2_yifu_suite.do"]
for fn in FILES:
    s = open(os.path.join(HERE, fn), encoding="utf-8").read()
    pat = re.compile(r"(absorb\([^)]*\)) robust")
    n0 = len(pat.findall(s)) + s.count("vce(robust)")
    s = pat.sub(r"\1 cluster(isocode)", s)
    s = s.replace("vce(robust)", "vce(cluster isocode)")
    # exported csv names
    s = re.sub(r'export delimited "(_[A-Za-z0-9_]+)\.csv"', r'export delimited "\1_cl.csv"', s)
    # temp dta names used by postfile/use/erase: suffix to avoid clashes with concurrent runs
    s = re.sub(r'"(_[A-Za-z0-9_]+_tmp)"', r'"\1_cl"', s)
    s = re.sub(r'"(_[A-Za-z0-9_]+_tmp)\.dta"', r'"\1_cl.dta"', s)
    s = s.replace("_feyrer_hetero_tot_post", "_feyrer_hetero_tot_post_cl")
    s = s.replace("_feyrer_hetero_post", "_feyrer_hetero_post_cl")
    s = s.replace('"_fey_mech_tmp"', '"_fey_mech_tmp_cl"').replace('"_fey_mech_tmp.dta"', '"_fey_mech_tmp_cl.dta"')
    head = "* COUNTRY-CLUSTERED COPY generated by _make_cl_dofiles.py on 2026-09-03 from " + fn + " (vce -> cluster(isocode); outputs *_cl.csv)\n"
    out = fn.replace(".do", "_cl.do")
    open(os.path.join(HERE, out), "w", encoding="utf-8").write(head + s)
    n1 = s.count("cluster(isocode)") + s.count("vce(cluster isocode)")
    exp = re.findall(r'export delimited "([^"]+)"', s)
    print(f"{out}: replaced {n0} -> cluster occurrences now {n1}; exports {exp}")
print("DONE")
