* COUNTRY-CLUSTERED COPY generated by _make_cl_dofiles.py on 2026-09-03 from co2_feyrer_mechanism.do (vce -> cluster(isocode); outputs *_cl.csv)
*==============================================================================
* co2_feyrer_mechanism.do
* MECHANISM DECOMPOSITION under the Feyrer air/sea IV.
* Identity: CO2 = flights x (seats/flight) x (km/seat) x (CO2/seat-km)
* so in logs: b(CO2) = b(flights) + b(gauge) + b(stage) + b(intensity).
* Outcomes:
*   ln_flights   = ln n_dep_flights            (frequency margin)
*   ln_gauge     = ln(dep_seats/n_dep_flights)  (aircraft up-gauging)
*   ln_stage     = ln(dep_seat_km/dep_seats)    (stage length)
*   ln_intensity = ln(CO2/seat-km)              (fuel intensity)
*   lto_share    = co2_lto/co2_bunker           (LTO amortisation)
*   intl_share   = dep_seat_km_intl/dep_seat_km (composition)
* Exports: _feyrer_mechanism.csv
*==============================================================================
clear all
set more off
set varabbrev off
set linesize 255
version 14
cd "C:/Users/sunbi/managi-lab Dropbox/Sunbin Yoo/Research Box ^-^/2026/GACI/GACI_CO2"

* ---- build merged dataset (same as co2_feyrer_full.do) ----
import delimited "co2_country_year.csv", clear varnames(1) encoding("utf-8")
keep iso3 year co2_bunker co2_bunker_intl co2_lto co2_5050 dep_seat_km n_dep_flights dep_seats dep_seat_km_intl
rename iso3 c
rename year y
tempfile co2
save `co2'

import delimited "../gaci_panel_combined.csv", clear varnames(1) encoding("utf-8")
ds c reg, not
destring `r(varlist)', replace force
merge 1:1 c y using `co2', keep(1 3) nogenerate
encode c, gen(isocode)
xtset isocode y

gen ln_co2_tot = ln(co2_bunker) if co2_bunker > 0
gen ln_skm = ln(dep_seat_km) if dep_seat_km > 0
gen ln_intensity = ln_co2_tot - ln_skm
gen ln_flights = ln(n_dep_flights) if n_dep_flights > 0
gen ln_gauge = ln(dep_seats/n_dep_flights) if n_dep_flights > 0 & dep_seats > 0
gen ln_stage = ln(dep_seat_km/dep_seats) if dep_seats > 0 & dep_seat_km > 0
gen lto_share = co2_lto/co2_bunker if co2_bunker > 0
gen intl_share = dep_seat_km_intl/dep_seat_km if dep_seat_km > 0
replace intl_share = 1 if intl_share > 1 & !missing(intl_share)

capture which ivreghdfe
if _rc {
    ssc install ftools, replace
    ssc install reghdfe, replace
    ssc install ivreghdfe, replace
}

* =====================================================================
* Mechanism outcomes, Feyrer IV
* =====================================================================
tempname M
postfile `M' str16 outc double(b se kpf) long(nn) using "_fey_mech_tmp_cl", replace
foreach yv in ln_co2_tot ln_skm ln_flights ln_gauge ln_stage ln_intensity lto_share intl_share {
    ivreghdfe `yv' lnpop ln_sea_ma (ln_gaci_cwm = feyrer_int), absorb(isocode y) cluster(isocode)
    di "MECH `yv': b = " %9.3f _b[ln_gaci_cwm] " (se " %8.3f _se[ln_gaci_cwm] ")  KP F = " %7.1f e(widstat) "  N = " %8.0f e(N)
    post `M' ("`yv'") (_b[ln_gaci_cwm]) (_se[ln_gaci_cwm]) (e(widstat)) (e(N))
}
postclose `M'
preserve
use "_fey_mech_tmp_cl", clear
list, clean
export delimited "_feyrer_mechanism_cl.csv", replace
restore
erase "_fey_mech_tmp_cl.dta"

* =====================================================================
* Identity check on common sample: b(CO2) = b(flights)+b(gauge)+b(stage)+b(int)
* =====================================================================
gen byte oksamp = !missing(ln_co2_tot) & !missing(ln_flights) & !missing(ln_gauge) & !missing(ln_stage) & !missing(ln_intensity) & !missing(lnpop) & !missing(ln_sea_ma) & !missing(feyrer_int) & !missing(ln_gaci_cwm)
local tot = 0
foreach yv in ln_flights ln_gauge ln_stage ln_intensity {
    quietly ivreghdfe `yv' lnpop ln_sea_ma (ln_gaci_cwm = feyrer_int) if oksamp, absorb(isocode y) cluster(isocode)
    di "IDCHK `yv' (common sample): b = " %9.4f _b[ln_gaci_cwm]
    local tot = `tot' + _b[ln_gaci_cwm]
}
quietly ivreghdfe ln_co2_tot lnpop ln_sea_ma (ln_gaci_cwm = feyrer_int) if oksamp, absorb(isocode y) cluster(isocode)
di "IDCHK sum of components = " %9.4f `tot' "   vs b(ln CO2) = " %9.4f _b[ln_gaci_cwm]

di _n "DONE_FEYRER_MECHANISM"
