* co2_exclusion_suite_cl_20260925.do: copy of co2_exclusion_suite_cl.do with the
* Venezuela trade/GDP zeros set to missing (affects Panel E only).
* Output: _exclusion_suite_cl_20260925.csv
* COUNTRY-CLUSTERED COPY generated by _make_cl_dofiles.py on 2026-09-03 from co2_exclusion_suite.do (vce -> cluster(isocode); outputs *_cl.csv)
*==============================================================================
* co2_exclusion_suite.do   (LZ comment 4, 2026-09-03)
* Exclusion-restriction diagnostics for the Feyrer instrument.
*   A  non-aviation placebo outcomes (RF and 2SLS)
*   B  horse race: aviation-technology x geography vs world GDP / oil / trade x geography
*   C  placebo instrument: a_t x ln sea market access 1996
*   D  zero-first-stage test: top baseline-connectivity tercile
*   E  development-channel controls, coefficient path
*   F  alternative technology series and distance-decay exponents
*   G  leads of the instrument
*   H  overidentification with the tourism instrument (Hansen J)
*   I  standard-error variants (cluster country, two-way, Conley HAC if acreg available)
* Inputs: gaci_panel_combined.csv, co2_country_year.csv, placebo_covariates.csv
* Export: _exclusion_suite.csv (panel item stat b se p f nn)
*==============================================================================
clear all
set more off
set varabbrev off
set linesize 255
version 14
cd "C:/Users/sunbi/managi-lab Dropbox/Sunbin Yoo/Research Box ^-^/2026/GACI/GACI_CO2"
log using "co2_exclusion_suite_cl_20260925_run.log", replace text

import delimited "co2_country_year.csv", clear varnames(1) encoding("utf-8")
keep iso3 year co2_bunker co2_bunker_intl dep_seat_km
rename iso3 c
rename year y
tempfile co2
save `co2'
import delimited "placebo_covariates.csv", clear varnames(1) encoding("utf-8")
ds c, not
destring `r(varlist)', replace force
tempfile plc
save `plc'

import delimited "../gaci_panel_combined.csv", clear varnames(1) encoding("utf-8")
ds c reg, not
destring `r(varlist)', replace force
merge 1:1 c y using `co2', keep(1 3) nogenerate
merge 1:1 c y using `plc', keep(1 3) nogenerate
* 2026-09-25: WDI returns 0 (not missing) for Venezuela trade/GDP 1991-2011
count if trade_gdp == 0
replace trade_gdp = . if trade_gdp == 0
encode c, gen(isocode)
xtset isocode y

gen ln_co2_tot = ln(co2_bunker) if co2_bunker > 0
gen ln_co2_intl = ln(co2_bunker_intl) if co2_bunker_intl > 0
gen ln_skm = ln(dep_seat_km) if dep_seat_km > 0
gen ln_intensity = ln_co2_tot - ln_skm

* baseline connectivity terciles (as in co2_feyrer_hetero.do)
bysort isocode (y): gen byte first_g = sum(!missing(gaci_cwmean)) == 1 & !missing(gaci_cwmean)
gen g0_ = gaci_cwmean if first_g
bysort isocode (g0_): gen gaci0 = g0_[1]
drop g0_ first_g
preserve
bysort isocode: keep if _n == 1
xtile con3 = gaci0, nq(3)
keep isocode con3
tempfile grp
save `grp'
restore
merge m:1 isocode using `grp', nogenerate

* leads of the instrument
sort isocode y
xtset isocode y
gen fey_lead3 = F3.feyrer_int
gen fey_lead5 = F5.feyrer_int

capture which ivreghdfe
if _rc {
    ssc install ftools, replace
    ssc install reghdfe, replace
    ssc install ivreghdfe, replace
}

tempname R
postfile `R' str10 panel str28 item str10 stat double(b se p f) long(nn) using "_excl_tmp_cl_0925", replace
global RH `R'

program define postrf
    * RF of `yv' on `iv' (plus controls), post coefficient on `iv'
    args panel item yv iv extra
    quietly reghdfe `yv' `iv' lnpop ln_sea_ma `extra', absorb(isocode y) vce(cluster isocode)
    local bb = _b[`iv']
    local sse = _se[`iv']
    local pp = 2*normal(-abs(`bb'/`sse'))
    di "RF  [`panel'] `item': b(`iv') = " %9.4f `bb' " (se " %8.4f `sse' ")  N = " %7.0f e(N)
    post $RH ("`panel'") ("`item'") ("RF") (`bb') (`sse') (`pp') (.) (e(N))
end

program define postiv
    * 2SLS of `yv' on ln_gaci_cwm instrumented by `iv' (plus controls)
    args panel item yv iv extra
    capture noisily ivreghdfe `yv' lnpop ln_sea_ma `extra' (ln_gaci_cwm = `iv'), absorb(isocode y) cluster(isocode)
    if _rc {
        di as err "IV FAILED [`panel'] `item'"
        exit
    }
    local bb = _b[ln_gaci_cwm]
    local sse = _se[ln_gaci_cwm]
    local pp = 2*normal(-abs(`bb'/`sse'))
    di "IV  [`panel'] `item': b = " %9.4f `bb' " (se " %8.4f `sse' ")  KP F = " %8.1f e(widstat) "  N = " %7.0f e(N)
    post $RH ("`panel'") ("`item'") ("IV") (`bb') (`sse') (`pp') (e(widstat)) (e(N))
end

program define postfs
    * first stage: ln_gaci_cwm on `iv' (plus extra), coefficient and partial F on `iv'
    args panel item iv extra
    quietly reghdfe ln_gaci_cwm `iv' lnpop ln_sea_ma `extra', absorb(isocode y) vce(cluster isocode)
    local bb = _b[`iv']
    local sse = _se[`iv']
    local pp = 2*normal(-abs(`bb'/`sse'))
    quietly test `iv'
    local ff = r(F)
    di "FS  [`panel'] `item': pi(`iv') = " %9.4f `bb' " (se " %8.4f `sse' ")  F = " %8.1f `ff' "  N = " %7.0f e(N)
    post $RH ("`panel'") ("`item'") ("FS") (`bb') (`sse') (`pp') (`ff') (e(N))
end

* =====================================================================
* A) placebo outcomes
* =====================================================================
di _n "===== A) non-aviation placebo outcomes ====="
foreach yv in ln_co2_tot ln_co2_intl ln_co2_exav ln_oil_exav ln_coal ln_gas ln_cement ln_ed_power ln_ed_build ln_ed_indcomb ln_ed_transp_exav ln_ed_agri {
    postrf A `yv' `yv' feyrer_int ""
    postiv A `yv' `yv' feyrer_int ""
}

* =====================================================================
* B) horse race on the content of the global cycle
* =====================================================================
di _n "===== B) horse race ====="
postfs B baseline feyrer_int ""
postiv B baseline ln_co2_tot feyrer_int ""
postfs B plus_gdp feyrer_int "fey_gdp"
postiv B plus_gdp ln_co2_tot feyrer_int "fey_gdp"
postfs B plus_oil feyrer_int "fey_oil"
postiv B plus_oil ln_co2_tot feyrer_int "fey_oil"
postfs B plus_trade feyrer_int "fey_trade"
postiv B plus_trade ln_co2_tot feyrer_int "fey_trade"
postfs B plus_all3 feyrer_int "fey_gdp fey_oil fey_trade"
postiv B plus_all3 ln_co2_tot feyrer_int "fey_gdp fey_oil fey_trade"
* the rival cycles as instruments on their own
foreach z in fey_gdp fey_oil fey_trade {
    postfs B own_`z' `z' ""
    postrf B own_`z' ln_co2_tot `z' ""
}

* =====================================================================
* C) placebo instrument: aviation technology x SEA geography
* =====================================================================
di _n "===== C) placebo instrument ====="
postfs C sea_alone fey_sea ""
postrf C sea_alone ln_co2_tot fey_sea ""
postrf C sea_alone_intl ln_co2_intl fey_sea ""
postfs C sea_with_air fey_sea "feyrer_int"
postrf C sea_with_air ln_co2_tot fey_sea "feyrer_int"
postfs C air_with_sea feyrer_int "fey_sea"
postrf C air_with_sea ln_co2_tot feyrer_int "fey_sea"
postiv C air_with_sea ln_co2_tot feyrer_int "fey_sea"

* =====================================================================
* D) zero-first-stage test (top baseline connectivity tercile)
* =====================================================================
di _n "===== D) zero first stage ====="
foreach g in 1 2 3 {
    quietly reghdfe ln_gaci_cwm feyrer_int lnpop ln_sea_ma if con3 == `g', absorb(isocode y) vce(cluster isocode)
    local bb = _b[feyrer_int]
    local sse = _se[feyrer_int]
    quietly test feyrer_int
    local ff = r(F)
    post $RH ("D") ("con`g'") ("FS") (`bb') (`sse') (2*normal(-abs(`bb'/`sse'))) (`ff') (e(N))
    di "FS  [D] con`g': pi = " %9.4f `bb' "  F = " %8.1f `ff'
    quietly reghdfe ln_co2_tot feyrer_int lnpop ln_sea_ma if con3 == `g', absorb(isocode y) vce(cluster isocode)
    local bb = _b[feyrer_int]
    local sse = _se[feyrer_int]
    post $RH ("D") ("con`g'") ("RF") (`bb') (`sse') (2*normal(-abs(`bb'/`sse'))) (.) (e(N))
    di "RF  [D] con`g': b = " %9.4f `bb' " (se " %8.4f `sse' ")"
    quietly reghdfe ln_intensity feyrer_int lnpop ln_sea_ma if con3 == `g', absorb(isocode y) vce(cluster isocode)
    local bb = _b[feyrer_int]
    local sse = _se[feyrer_int]
    post $RH ("D") ("con`g'_intens") ("RF") (`bb') (`sse') (2*normal(-abs(`bb'/`sse'))) (.) (e(N))
}

* =====================================================================
* E) development-channel controls (coefficient path)
* =====================================================================
di _n "===== E) control path ====="
postiv E c0_baseline ln_co2_tot feyrer_int ""
postiv E c1_gdp ln_co2_tot feyrer_int "lngdp"
postiv E c2_trade ln_co2_tot feyrer_int "lngdp trade_gdp"
postiv E c3_urban ln_co2_tot feyrer_int "lngdp trade_gdp urban"
postiv E c4_fdi ln_co2_tot feyrer_int "lngdp trade_gdp urban fdi"
postiv E c5_arrivals ln_co2_tot feyrer_int "lngdp trade_gdp urban fdi ln_arrivals"
gen byte okctrl = !missing(lngdp, trade_gdp, urban, fdi, ln_arrivals, ln_co2_tot, ln_gaci_cwm, feyrer_int, lnpop, ln_sea_ma)
capture noisily ivreghdfe ln_co2_tot lnpop ln_sea_ma (ln_gaci_cwm = feyrer_int) if okctrl, absorb(isocode y) cluster(isocode)
post $RH ("E") ("c0_commonsample") ("IV") (_b[ln_gaci_cwm]) (_se[ln_gaci_cwm]) (2*normal(-abs(_b[ln_gaci_cwm]/_se[ln_gaci_cwm]))) (e(widstat)) (e(N))
di "IV  [E] common-sample baseline: b = " %9.4f _b[ln_gaci_cwm] " (se " %8.4f _se[ln_gaci_cwm] ")  N = " %7.0f e(N)

* =====================================================================
* F) alternative technology series and decay exponents
* =====================================================================
di _n "===== F) alternative shifters ====="
foreach z in feyrer_int fey_th10chk fey_fl fey_skm fey_gaci fey_eff fey_th05 fey_th15 {
    postfs F `z' `z' ""
    postiv F `z' ln_co2_tot `z' ""
}

* =====================================================================
* G) leads of the instrument
* =====================================================================
di _n "===== G) leads ====="
quietly reghdfe ln_co2_tot feyrer_int fey_lead3 lnpop ln_sea_ma, absorb(isocode y) vce(cluster isocode)
post $RH ("G") ("lead3_current") ("RF") (_b[feyrer_int]) (_se[feyrer_int]) (2*normal(-abs(_b[feyrer_int]/_se[feyrer_int]))) (.) (e(N))
post $RH ("G") ("lead3_lead") ("RF") (_b[fey_lead3]) (_se[fey_lead3]) (2*normal(-abs(_b[fey_lead3]/_se[fey_lead3]))) (.) (e(N))
di "RF  [G] with lead3: current = " %8.4f _b[feyrer_int] " (se " %7.4f _se[feyrer_int] ")  lead3 = " %8.4f _b[fey_lead3] " (se " %7.4f _se[fey_lead3] ")"
quietly reghdfe ln_co2_tot feyrer_int fey_lead5 lnpop ln_sea_ma, absorb(isocode y) vce(cluster isocode)
post $RH ("G") ("lead5_current") ("RF") (_b[feyrer_int]) (_se[feyrer_int]) (2*normal(-abs(_b[feyrer_int]/_se[feyrer_int]))) (.) (e(N))
post $RH ("G") ("lead5_lead") ("RF") (_b[fey_lead5]) (_se[fey_lead5]) (2*normal(-abs(_b[fey_lead5]/_se[fey_lead5]))) (.) (e(N))
di "RF  [G] with lead5: current = " %8.4f _b[feyrer_int] " (se " %7.4f _se[feyrer_int] ")  lead5 = " %8.4f _b[fey_lead5] " (se " %7.4f _se[fey_lead5] ")"
quietly reghdfe ln_gaci_cwm feyrer_int fey_lead3 lnpop ln_sea_ma, absorb(isocode y) vce(cluster isocode)
post $RH ("G") ("lead3_fs_current") ("FS") (_b[feyrer_int]) (_se[feyrer_int]) (2*normal(-abs(_b[feyrer_int]/_se[feyrer_int]))) (.) (e(N))
post $RH ("G") ("lead3_fs_lead") ("FS") (_b[fey_lead3]) (_se[fey_lead3]) (2*normal(-abs(_b[fey_lead3]/_se[fey_lead3]))) (.) (e(N))

* =====================================================================
* H) overidentification with tourism instrument
* =====================================================================
di _n "===== H) Hansen J ====="
capture noisily ivreghdfe ln_co2_tot lnpop ln_sea_ma (ln_gaci_cwm = feyrer_int tourism_int), absorb(isocode y) cluster(isocode)
if !_rc {
    post $RH ("H") ("feyrer_plus_tourism") ("IV") (_b[ln_gaci_cwm]) (_se[ln_gaci_cwm]) (2*normal(-abs(_b[ln_gaci_cwm]/_se[ln_gaci_cwm]))) (e(widstat)) (e(N))
    post $RH ("H") ("hansen_j") ("J") (e(j)) (.) (e(jp)) (.) (e(N))
    di "IV  [H] two instruments: b = " %9.4f _b[ln_gaci_cwm] "  KP F = " %8.1f e(widstat) "  Hansen J = " %8.3f e(j) "  p = " %6.3f e(jp)
}
capture noisily ivreghdfe ln_co2_tot lnpop ln_sea_ma (ln_gaci_cwm = tourism_int), absorb(isocode y) cluster(isocode)
if !_rc {
    post $RH ("H") ("tourism_alone") ("IV") (_b[ln_gaci_cwm]) (_se[ln_gaci_cwm]) (2*normal(-abs(_b[ln_gaci_cwm]/_se[ln_gaci_cwm]))) (e(widstat)) (e(N))
}

* =====================================================================
* I) standard-error variants
* =====================================================================
di _n "===== I) SE variants ====="
ivreghdfe ln_co2_tot lnpop ln_sea_ma (ln_gaci_cwm = feyrer_int), absorb(isocode y) cluster(isocode)
post $RH ("I") ("robust") ("IV") (_b[ln_gaci_cwm]) (_se[ln_gaci_cwm]) (2*normal(-abs(_b[ln_gaci_cwm]/_se[ln_gaci_cwm]))) (e(widstat)) (e(N))
ivreghdfe ln_co2_tot lnpop ln_sea_ma (ln_gaci_cwm = feyrer_int), absorb(isocode y) cluster(isocode)
post $RH ("I") ("cluster_country") ("IV") (_b[ln_gaci_cwm]) (_se[ln_gaci_cwm]) (2*normal(-abs(_b[ln_gaci_cwm]/_se[ln_gaci_cwm]))) (e(widstat)) (e(N))
di "IV  [I] cluster country: se = " %8.4f _se[ln_gaci_cwm] "  KP F = " %8.1f e(widstat)
ivreghdfe ln_co2_tot lnpop ln_sea_ma (ln_gaci_cwm = feyrer_int), absorb(isocode y) cluster(isocode y)
post $RH ("I") ("cluster_twoway") ("IV") (_b[ln_gaci_cwm]) (_se[ln_gaci_cwm]) (2*normal(-abs(_b[ln_gaci_cwm]/_se[ln_gaci_cwm]))) (e(widstat)) (e(N))
di "IV  [I] two-way cluster: se = " %8.4f _se[ln_gaci_cwm] "  KP F = " %8.1f e(widstat)

postclose `R'
preserve
use "_excl_tmp_cl_0925", clear
list, clean noobs
export delimited "_exclusion_suite_cl_20260925.csv", replace
restore
erase "_excl_tmp_cl_0925.dta"

di _n "DONE_EXCLUSION_SUITE"
log close
